astro-reactive/astro-reactive

packages/astro-reactive-form/core/form-control.ts, packages/astro-reactive-form/core/form-group.ts
=> Fix #6: refactored IFormControl to FormControlBase and added radio prop.

README.md
=> Add contributor pictures to the project README

packages/astro-reactive-form/index.ts
=> [feat]: export all from Form.astro

packages/astro-reactive-form/Form.astro
let's see if automated tests catch this
=> experiment: breaking commit

.github/workflows/build-and-test.yml, .gitignore
=> devops: update build stage; ignore dist

.github/pull_request_template.md, README.md, packages/astro-reactive-form/README.md
- simplify pull request templage
- display last commit badge
=> Docs update readme

package-lock.json, packages/astro-reactive-form/README.md, packages/astro-reactive-form/package.json
What is this PR about? docs / bugfix / feature
-
-
Tasks:
=> chore: update deps

package.json, packages/astro-reactive-form/package.json
What is this PR about? (docs, fix, feature, style, devops, etc.)
-
Related issue number: #
-
Tag a reviewer: @
Tasks:
=> chore: bump patch; update script

packages/astro-reactive-form/core/form-control.ts, packages/astro-reactive-form/core/form-group.ts, packages/astro-reactive-form/types.ts
What is this PR about? refactoring
- Refactoring the astro-reactive-form directory
- Maintaining the types of the package
Issue: #24  
- created a separate types.ts file inside the astro-reactive-form directory storing all the types
Tasks:
=> [refactor]: astro-reactive-form types

demo/src/pages/index.astro, packages/astro-reactive-form/components/Field.astro, packages/astro-reactive-form/core/form-control.ts, packages/astro-reactive-form/types.ts
What is this PR about?
Implement Form Control Placeholder
-
Related issue number: #43
- Add placeholder to `FormControl` interface
- Add placeholder attribute to`Field` component
Tasks:
=> [feat]: Form control placeholder attribute

CONTRIBUTING.md
https://github.com/ayoayco/astro-reactive-library/issues/49
What is this PR about? (docs)
-
Related issue number: #49 
- Added links as requested
Tasks:
=> #49 [docs]: add links to docs

apps/landing-page/src/components/copynpm.astro, apps/landing-page/src/components/splash.astro
Fixes #115  
Screenshot of UI Changes:
Tasks:
=> feat(landing-page): Adding Call-to-action buttons

package-lock.json, packages/configs/.eslintrc.cjs, packages/form/.eslintrc.cjs, packages/validator/.eslintrc.cjs
Fixes #94  
- Initialized a npm package.json in root of packages.
- Added shared Eslint and Prettier configs.
Problems:
- Changes break the demo app as I don't why but somehow imports are getting messed up in demo app (help needed)
Note:
Make sure to do a quick npm install after pulling changes.
Tasks:
=> chore: Shared eslint + prettier for packages

packages/form/test/Field.astro.test.js, packages/form/test/FieldSet.astro.test.js
Fixes #41  
- Added couple of tests for Field and FieldSet components
Tasks:
=> test(packages/form): Added some tests for Field and FieldSet components

apps/demo/src/pages/demo.astro, apps/demo/src/pages/pizza-delivery.astro
#[feat]: Add a new demo page
Fixes #68  
- Created a new demo form for a hypothetical pizza shop. 
-
Tasks:
=> [feat]: Add a new demo page

apps/landing-page/src/components/copynpm.astro, apps/landing-page/src/components/splash.astro, apps/landing-page/tailwind.config.cjs, package-lock.json
Fixes #118  
Changes have been made in the styling of the pages.
Tasks:
=> fix responsiveness of landing-page

package.json
Fixes #145 
Added `npm outdated` command in `package.json` file for `patch`, `minor`, and `major` commands.
Tag a reviewer: @ayoayco
=> chore: added `npm outdated` command for `patch`,`minor`, and `major` commands

apps/landing-page/src/components/copynpm.astro, apps/landing-page/src/components/splash.astro, apps/landing-page/src/components/starfield.astro, apps/landing-page/src/pages/index.astro, apps/landing-page/src/sections/astro-section.astro, package-lock.json
Fixes #133  
- Added astro section as discussed in discussion #112 
Tasks:
=> ui(landing-page): Added astro section

README.md
Fixes #137 
- added stackblitz link in readme
Tasks:
=> docs(add link stackblitz)

README.md
Files changed:
- Readme.md
Fixes #152 
- Updated the readme.md to go to the respective release files 
Tasks:
- [x ] I have ran the build command to make sure apps are working: `npm run build`
- [x ] I have ran the tests to make sure nothing is broken: `npm run test`
- [x ] I have ran the linter to make sure code is clean: `npm run lint`
- [x ] I have reviewed my own code to remove changes that are not needed
=> docs: updating readme.md package tables

README.md
Fixes #156 
Tag a reviewer: @ayoayco
=> docs: fix stackblitz link on readme

README.md
Fixes #137 
- added link to codesandbox example 
Tasks:
=> docs(codesandbox): added link to codesandbox example

apps/demo/astro.config.mjs, apps/demo/src/pages/index.astro, apps/demo/src/pages/job-application.astro, apps/demo/src/pages/pizza-delivery.astro
Fixes #162 
- Added a new demo page representing a job application form.
- Linked the new page in the existing pages (index.astro and pizza-delivery.astro).
Picture of job application demo page:
Tasks:
=> feat: add a new demo page!

package-lock.json, packages/form/components/Field.astro, packages/form/components/FieldSet.astro, packages/form/components/Form.astro, packages/form/components/controls/Dropdown.astro, packages/form/components/controls/Input.astro, packages/form/components/controls/RadioGroup.astro, packages/form/test/Dropdown.astro.test.js, packages/form/test/Field.astro.test.js, packages/form/test/Form.astro.test.js, packages/form/test/RadioGroup.astro.test.js
Fixes #144
- Write tests for adding new prop readOnly
- Add readOnly prop to Form and all the subsequent inputs
Tag a reviewer: @ayoayco
Tasks:
=> Add readOnly flag on form

packages/form/components/controls/RadioGroup.astro, packages/form/test/RadioGroup.astro.test.js, packages/form/test/utils/index.js
=> feat(form): add index to radio group item id

apps/docs/astro.config.mjs
Fixes #190 
- Change a site option in docs config
Tasks:
=> chore(docs): change site option

.github/workflows/build-and-test.yml, package.json, packages/form/vitest.config.ts, packages/validator/test/Validator.astro.test.ts, packages/validator/vitest.config.ts, turbo.json
Fixes #207
-  Add timeout and retry to failing test
Tasks:
=> fix: extends timeout for timed out test

CONTRIBUTING.md, apps/docs/src/config.ts, apps/landing-page/src/components/header.astro
- update contributing doc, mention turborepo and discord
- update docs site to link to discord
- update landing page to show link to discord
=> feat(docs, landing-page): mention turborepo and link to discord

apps/docs/src/pages/en/api/form/form-component.md, apps/landing-page/src/components/copynpm.astro
- Mentioned validateOnLoad prop for Form component in docs.
Tasks:
=> docs: Mentioned validateOnLoad prop for Form component

apps/demo/src/pages/index.astro, apps/docs/src/config.ts, apps/docs/src/pages/en/api/validator/index.astro, apps/docs/src/pages/en/api/validator/validators.md
Fixes #195  
- Adding initial documentation for validators package.
Tasks:
=> docs(Validators): Added docs for validators.

packages/form/core/form-control.ts, packages/form/core/form-group.ts, packages/validator/core/validator-functions.ts, packages/validator/core/validator-names.ts
Fixes #188 
- Add JSDocs to packages' exported API/methods 
Tag a reviewer: @ayoayco @Icyscools 
Tasks:
=> feat: Types and Intellisense Improvements

apps/docs/src/pages/en/api/validator/validators.md
Fixes #229 
Modified validators.min and validators.max docs as mentioned in issue #229 .
Tasks:
=> modifify validators docs

package-lock.json, packages/common/package.json, packages/common/tsconfig.json, packages/form/package.json, packages/form/tsconfig.json, packages/validator/package.json, turbo.json
Fixes #239 
- change internal packages reference to use `*` instead of latest.
- turborepo `check` step depends on packages' build.
Tasks:
=> fix(form): internal package on local dev environment symlinked to node_modules 

apps/demo/src/pages/index.astro, packages/form/README.md, packages/validator/README.md
=> docs: update example in form readme

apps/landing-page/src/components/splash.astro
=> refactor: remove fart

README.md, apps/demo/package.json, apps/docs/package.json, apps/landing-page/package.json, apps/landing-page/tailwind.config.cjs, configs/tsconfig/base.json, package-lock.json, packages/form/package.json, packages/form/src/env.d.ts, packages/validator/.eslintignore, packages/validator/package.json, packages/validator/src/env.d.ts
Fixes #262 
- Update `astro` to `2.13` to all workspace
- Update breaking dependencies because of `astro` breaking changes
Tasks:
=> chore: update astro to v2

.changeset/hot-buses-repeat.md, LICENSE, apps/demo/package.json, apps/docs/package.json, apps/landing-page/package.json, package.json, packages/common/package.json, packages/create-astro-reactive/README.md, packages/create-astro-reactive/index.js, packages/create-astro-reactive/package.json, packages/form/package.json, packages/validator/package.json
- Initial `create-astro-reactive` package
- Update packages' meta information (author, homepage)
- Upadte LICENSE owner info to `astro-reactive` organization
Tasks:
=> feat: initialize create-astro-reactive package

apps/landing-page/src/components/starfield.astro
Make animation slower and less frequent
=> feat(landing page): slower animation
