astro-reactive/astro-reactive

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, CODE_OF_CONDUCT.md, LICENSE
Adds the recommended GitHub community standards to make the project contributor friendly.
fixes #26 
I left the pull request template blank deliberately because you were working on it.
=> [chore]: implement recommended community standards

packages/astro-reactive-form/Form.astro, packages/astro-reactive-form/core/form-group.ts
What is this PR about? (docs, fix, feature, style, devops, etc.)
-
This PR is to implement a feature to limit the form component to at most 1 submit control.
Related issue number: #23
-
I added a new optional `submitControl` prop in the `Form.astro` component and implemented a limit to the `FormGroup` constructor to not accept control type `submit`.
Tasks:
=> feat: implement form submit button limit

packages/astro-reactive-form/Form.astro, packages/astro-reactive-form/test/Form.astro.test.js
What is this PR about? Implement `Form` component theme props
-
Related issue number: #9 
- Add optional `theme` props to `Form.astro` that dynamically set the color theme.
Tasks:
=> [feat]: Implement form theme

apps/demo/src/pages/index.astro, packages/form/Form.astro, packages/form/components/Field.astro, packages/form/core/form-control-types.ts, packages/form/core/form-control.ts
Related with #5 
This pull request is intended to make a radio type work.
However, it was more difficult than I expect, so I did take a lot of time and made a lot of changes to make it work. 😂
Please review and request me back if you don't need some changes or catch some mistakes.
The summary of changes are 
- Added two types of radios, one is `string[]` and the other is `RadioOption[]` that I extend from `ControlBase` (which I suggest both types in #5) and added examples of both types in a demo.
- Added `id` property in `ControlBase` to make a custom id. This property is used for linking the label to the input radio.
- Added `showOnlyLabel` prop in `Field.astro`. I used this prop to show only the label for a `FormControl` which I use for displaying the label of a radio. (look in line 27 …
=> feat(form): Implement radio type

apps/landing-page/src/components/copynpm.astro
Fixes #126 
- Added id in button and span tag to get the element by ID.
- Created a vanilla JavaScript function and added it to as event listener on click of button to get the `innerText` of `span tag` using its ID.
Tasks:
=> Copy to Clipboard Functionality Added on Landing Page

apps/demo/src/pages/index.astro, apps/demo/src/pages/pizza-delivery.astro, packages/common/types/control.types.ts, packages/form/components/controls/RadioGroup.astro, packages/form/core/form-control.ts, packages/form/test/RadioGroup.astro.test.js
Fixes #142 
- Implement `options` prop for `Radio` control.
- Modify the behavior of `value` for `Radio` so that it now checks the radio options with the same value as `value`.
- Remove the `checked` property from the `RadioOption` type because we no longer need it to check a checked radio option.
- Refactor radio options on demo pages to use this change.
- Add some tests to validate this change.
Tasks:
=> refactor(form): implement `options` prop for Radio

apps/demo/src/pages/index.astro, packages/common/types/control.types.ts, packages/form/components/Field.astro, packages/form/components/controls/Dropdown.astro, packages/form/components/controls/Input.astro, packages/form/components/controls/RadioGroup.astro, packages/form/core/form-control.ts, packages/form/test/Dropdown.astro.test.js, packages/form/test/RadioGroup.astro.test.js
feat(form): Add Dropdown Control
Fixes #143 
- Implement a `Dropdown.astro` control.
- Add `Dropdown` and `DropdownOption` type. 
These types have attributes like `Radio` and `RadioOption` types but I created it for use in case the dropdown has different attributes than that in the future.
- Include tests on a `Dropdown` control.
Tasks:
=> feat(form): add Dropdown control

packages/form/components/Label.astro
fix(form): asterisks on required field in `Label.astro`
Fixes #104 
This approach is same as a recently fix PR on this issue.
- Change the way to display an asterisk from text to ::before pseudo-classes
Tasks:
=> fix(form): asterisks on required field in `Label.astro`

apps/demo/src/pages/index.astro, packages/common/types/control.types.ts, packages/form/components/Field.astro, packages/form/components/controls/TextArea.astro, packages/form/core/form-control.ts, packages/form/test/TextArea.astro.test.js
Fixes #161 
- Implement `TextArea` control which include `TextArea.astro` and `TextArea` common type.
- The default values of TextArea for `rows` is 3 and `cols` is 21.
(This is the closest width with the default text input form that I try to play around with).
- Include some tests for `TextArea` control.
Tasks:
=> feat(form): implement TextArea control

apps/demo/src/pages/index.astro, apps/docs/src/pages/en/page-2.md, packages/common/types/control.types.ts, packages/form/README.md, packages/form/components/Form.astro, packages/form/components/Label.astro, packages/form/components/controls/Input.astro, packages/form/components/controls/TextArea.astro, packages/form/core/form-control.ts, packages/form/test/Field.astro.test.js, packages/form/test/FieldSet.astro.test.js, packages/validator/README.md
Fixes #139  
- Remove all `labelPosition` properties and its related in packages, types, tests, demos, and also in docs.
- Label position for checkboxes now will be only right side.
Tasks:
=> refactor(form): deprecate labelPosition

package-lock.json, package.json, packages/form/components/FieldSet.astro, packages/form/components/Form.astro, packages/form/components/Label.astro, packages/form/components/controls/Dropdown.astro, packages/form/components/controls/Input.astro, packages/form/components/controls/RadioGroup.astro, packages/form/components/controls/TextArea.astro, packages/form/core/form-control.ts, packages/form/core/form-group.ts
Fixes #140 
- Added a `npm` library: [Short Unique ID (UUID) Generating Library](https://github.com/simplyhexagonal/short-unique-id)
- Used for generating unique IDs for form components
- Added ID properties to both `form-control` and `form-group`
- Replaced all instances in the components where `id` is assigned the `name` value to use the `id` value instead.
- Added an `id` value to `RadioGroup` as there was none before.
Note: When I ran `npm run test`, some tests failed but those same tests also failed before I made any changes.
Tasks:
=> feat(form): implement unique IDs

apps/demo/src/pages/job-application.astro, packages/form/core/form-group.ts
Fixes #175  
- Created a new `setValue` method in the FormGroup class which will set the values for any FormControls in the FormGroup.
- Updated the job application demo page to use the new `setValue` method. For example the following code:
will produce the following page:
Tasks:
=> feat(form): add `setValue` method to FormGroup class

package-lock.json, packages/form/package.json, packages/form/test/Dropdown.astro.test.ts, packages/form/test/Field.astro.test.ts, packages/form/test/FieldSet.astro.test.ts, packages/form/test/Form.astro.test.ts, packages/form/test/RadioGroup.astro.test.ts, packages/form/test/TextArea.astro.test.ts, packages/form/test/utils/index.ts, packages/form/vitest.config.ts, packages/validator/package.json, packages/validator/test/Validator.astro.test.ts, packages/validator/vitest.config.ts
Fixes #194 
- Migrate test tooling to [Vitest](https://vitest.dev/guide/why.html)
- Migrate test files to typescript
Tasks:
=> test(migrate): migrate test tooling from chai + mocha to vitest

packages/validator/Validator.astro
Fixes #141 
- Use a `checked` attribute instead of a `value` attribute for checkboxes input form.
Tasks:
=> fix(validator): use a checked attribute for required validation in checkboxes

packages/form/components/Field.astro, packages/form/components/Form.astro, packages/form/components/controls/Input.astro
- validation attributes are now set to null instead of false, so the attribute will not be rendered resulting in cleaner HTML
- validation-info is now green instead of blue
Tag a reviewer: @Lalit3716 / @Icyscools 
Tasks:
=> refactor(form): validation attributes set null instead of false

packages/form/test/Field.astro.test.ts
- Added a test for testing category validator prop.
Tag a reviewer: @ayoayco, @Icyscools, @fazzaamiarso 
Tasks:
=> test(form): Added test Field.astro to test for category validation prop

apps/landing-page/src/components/copynpm.astro
Fixes #197  
- Displaying a toast on clicking copy button!
Tag a reviewer: @ayoayco, @fazzaamiarso, @Preet-Sojitra 
Tasks:
=> style(landing-page): Displaying toast on clicking copy button

packages/common/types/control.types.ts, packages/common/types/validator.types.ts, packages/form/components/controls/Dropdown.astro, packages/form/components/controls/Input.astro, packages/form/components/controls/RadioGroup.astro, packages/form/components/controls/TextArea.astro, packages/form/core/form-control.ts, packages/validator/Validator.astro
Fixes #201 
- Created a new type in [validator.types.ts](https://github.com/alexsam29/astro-reactive-library/blob/9ee7442b389207960ab0b14c354bbd8d2cecac63/packages/common/types/validator.types.ts#L3) called `ValidationHooks`.
- This is used to define different types of event listeners. I only added 3 basic ones (`blur`, `keypress`, and `click`), but more can and should be added.
- Added a new attribute to the interface `ControlBase` in [control.types.ts](https://github.com/alexsam29/astro-reactive-library/blob/9ee7442b389207960ab0b14c354bbd8d2cecac63/packages/common/types/control.types.ts#L40) called ` triggerValidationOn`
- This will hold the user specified event listener
- Added an additional class variable in …
=> feat(form): implement FormControl and ControlConfig prop `triggerValidationOn`

packages/form/components/controls/RadioGroup.astro, packages/form/test/RadioGroup.astro.test.ts
Fixes #230 
- Added support for `RadioGroup` validation
- Removed `<div>` element covering the `<input>` and `<label>` elements of `RadioGroup`. This was most likely interfering with validation.
- Also added `<br>` elements for formatting purposes. Otherwise the radio buttons would be on the same line. Can remove if it's not necessary.
The first test is failing right now in `RadioGroup.astro.test.ts`, but I suspect it's due to the removal of the `<div>` element. It's not recognizing the radio options without it. I can fix this as well in the same PR, if required.
Tag a reviewer: @Icyscools @ayoayco 
Tasks:
=> feat(validator): add validation support for `RadioGroup`

package-lock.json, package.json, packages/pr-updater.js
Fixes #148 
- Added the [prompt-sync](https://www.npmjs.com/package/prompt-sync) and [semver](https://www.npmjs.com/package/semver) packages.
- Created a script `pr-updater.js` located in the `packages` directory that can be run using `npm run release`. This script will prompt the contributor for the package changed, the type of PR, and the description(s) of changes made. Then, the script will find the corresponding RELEASE.md file and update it.
For example, the running the script:
Will produce the following RELEASE.md:
Tasks:
=> chore: create script for updating RELEASE.md before PR

apps/demo/src/pages/index.astro, packages/common/types/control.types.ts, packages/form/components/Form.astro, packages/form/test/Form.astro.test.ts
Fixes #236 
- add new properties `action` and `method` which handle a form action like a standard form.
- add a `HTTPRequestMethodType` for typing HTTP request methods.
- add some tests for it.
- enhance a demo page for this improvement.
Tag a reviewer: @ayoayco
Tasks:
=> feat(form): add form action for submitting form

.changeset/sour-bobcats-peel.md, apps/demo/src/pages/index.astro, packages/form/components/Form.astro, packages/form/core/form-control.ts
Fixes #283 
1. Change the default of `validateOnLoad` property to true, making server-side rendering validation the default behavior for the `Form` component.
1. Update the demo `index.astro` page by removing the `validateOnLoad` property/directive on the example which should still result to server-side rendered validation results.
Tag a reviewer: @Icyscools @fazzaamiarso 
Tasks:
=> feat(form): change validate on load to true by default
